![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### 2.2.3 Foydali funksiyalar

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
       'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
       'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
       'Zichlik':[79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [ ]:
df.index = [21, 20, 19, 18, 17, 16, 15, 10]
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

## `.reindex()` indekslar o'rnini almashtirish

In [ ]:
df.reindex([10,15,20])

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
20  2020        33.5  1.48    78.68

`.reindex` yordamida yangi indekslar qo'shish va ularni turli usullar (method) yordamida to'ldirish ham mumkin

In [ ]:
df.reindex(index=range(10,22), method="nearest") # method='ffill'

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2010        28.5  1.53    67.03
12  2010        28.5  1.53    67.03
13  2015        30.9  1.64    72.71
14  2015        30.9  1.64    72.71
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

Nafaqat indekslarni balki ustunlarni ham qayta indekslash mumkin

In [ ]:
df.reindex(columns=['Aholi soni','Temp'])

    Aholi soni  Temp
21        33.9  1.54
20        33.5  1.48
19        32.9  1.56
18        32.5  1.62
17        31.9  1.65
16        31.4  1.66
15        30.9  1.64
10        28.5  1.53

### `.loc` yordamida indekslash

In [ ]:
df.loc[[10,15,20],['Aholi soni','Temp']]

    Aholi soni  Temp
10        28.5  1.53
15        30.9  1.64
20        33.5  1.48

**DIQQAT! DataFrame metodlati asl DataFrameni o'zgartirmaydi, balki yangi (o'zgartirilgan) DataFrame qaytaradi.**

## `DataFrame`dan elementlarni o'chirish. `.drop()`

Dataframedan biror qator yoki ustunni o'chirish uchun qator (ustun) indeksini bilish kifoya.

In [ ]:
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [ ]:
df_new = df.drop(10) # 10 indeksini o'chiramiz va yangi df yaratamiz

In [ ]:
df_new

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71

In [ ]:
df.drop([15, 20]) # 15 va 20 qatorlarini tashlab yuboramiz

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
10  2010        28.5  1.53    67.03

`.drop()` yordamida nafaqat qatorlarni, balki ustunlarni ham o'chirish mumkin. Buning `.drop()` metodining `axis` parametri ishlatiladi.

In [ ]:
df.drop('Temp', axis=1) # axis=1 ustunni anglatadi, axis=0 esa qatorni

     Yil  Aholi soni  Zichlik
21  2021        33.9    79.77
20  2020        33.5    78.68
19  2019        32.9    77.53
18  2018        32.5    76.34
17  2017        31.9    75.13
16  2016        31.4    73.91
15  2015        30.9    72.71
10  2010        28.5    67.03

In [ ]:
df.drop('Temp', axis='columns') # bu usul ham yuqoridagi natijani beradi

     Yil  Aholi soni  Zichlik
21  2021        33.9    79.77
20  2020        33.5    78.68
19  2019        32.9    77.53
18  2018        32.5    76.34
17  2017        31.9    75.13
16  2016        31.4    73.91
15  2015        30.9    72.71
10  2010        28.5    67.03

Yana bir bor eslatamiz, metodlar asl `DataFrame`ni o'zgartirmaydi.

In [ ]:
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

Lekin buning ham imkoni bor. Odatda `.drop()` kabi metodlar maxsus `inplace` parametri bilan keladi va bu parametr standart `False` qiymatga ega bo'ladi (`inplace=False`)

In [ ]:
df.drop('Yil', axis=1, inplace=True)

In [ ]:
df.head() # E'tibot bering endi Yil ustini yo'q

    Aholi soni  Temp  Zichlik
21        33.9  1.54    79.77
20        33.5  1.48    78.68
19        32.9  1.56    77.53
18        32.5  1.62    76.34
17        31.9  1.65    75.13

### Indekslash, qator (ustun) tanlash, filtrlash

### `Series`

In [ ]:
data = df['Aholi soni'] # Series obyekt yaratib olamiz

In [ ]:
data

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: Aholi soni, dtype: float64

In [ ]:
data[0:2] # 0 va 1 elementlar qaytadi

21    33.9
20    33.5
Name: Aholi soni, dtype: float64

In [ ]:
data[[21]]

21    33.9
Name: Aholi soni, dtype: float64

In [ ]:
data[[21,19,17]]

21    33.9
19    32.9
17    31.9
Name: Aholi soni, dtype: float64

In [ ]:
obj = pd.Series(np.arange(8.), index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [ ]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [ ]:
obj[['b']]

pandas.core.series.Series

In [ ]:
type(obj[['b']])

pandas.core.series.Series

In [ ]:
obj['b']

1.0

In [ ]:
type(obj['b'])

numpy.float64

In [ ]:
obj[0:4] # 0,1,2,3 indeksdagi qiymatlar 4 kirmaydi

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
obj['a':'f'] # a,b,c,d,e,f chiqadi.

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64

In [ ]:
obj[['c','d','f']]

c    2.0
d    3.0
f    5.0
dtype: float64

In [ ]:
obj[[1,5]]

b    1.0
f    5.0
dtype: float64

In [ ]:
obj['a':'d']=22

In [ ]:
obj

a    22.0
b    22.0
c    22.0
d    22.0
e     4.0
f     5.0
g     6.0
h     7.0
dtype: float64

In [ ]:
obj[obj==22]

a    22.0
b    22.0
c    22.0
d    22.0
dtype: float64

In [ ]:
obj[obj<22]

e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

### `DataFrame`

In [ ]:
uz = {2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9, 2016:31.4, 2015:30.9}
kz = {2020:18.8, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8, 2015:17.6}
tj = {2020:9.5, 2019:9.3, 2018:9.1, 2017:8.9, 2016:8.7, 2015:8.5}
kg = {2020:6.5, 2019:6.4, 2018:6.3, 2017:6.2, 2016:6.1, 2015:6.0}
tr = {2020:6.0, 2019:5.9, 2018:5.9, 2017:5.8, 2016:5.6, 2015:5.6}

df = pd.DataFrame(
    {'Uzbekistan':uz,
     'Kazakhstan':kz,
     'Tajikistan':tj,
     'Kyrgizstan':kg,
     'Turkmenistan':tr
    }
)

In [ ]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df['Uzbekistan']

2020    33.5
2019    32.9
2018    32.5
2017    31.9
2016    31.4
2015    30.9
Name: Uzbekistan, dtype: float64

In [ ]:
df[['Uzbekistan']]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [ ]:
df[['Uzbekistan','Turkmenistan']]

      Uzbekistan  Turkmenistan
2020        33.5           6.0
2019        32.9           5.9
2018        32.5           5.9
2017        31.9           5.8
2016        31.4           5.6
2015        30.9           5.6

In [ ]:
df[3:]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df>8

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        True        True        True       False         False
2019        True        True        True       False         False
2018        True        True        True       False         False
2017        True        True        True       False         False
2016        True        True        True       False         False
2015        True        True        True       False         False

In [ ]:
df[['Uzbekistan']][df['Uzbekistan']>32]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5

In [ ]:
df2=df.transpose(copy=True)

In [ ]:
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan     9.5   9.3   9.1   8.9   8.7   8.5
Kyrgizstan     6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.9   5.9   5.8   5.6   5.6

In [ ]:
df2[df2[2015]>6]

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan  18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan   9.5   9.3   9.1   8.9   8.7   8.5

In [ ]:
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan     9.5   9.3   9.1   8.9   8.7   8.5
Kyrgizstan     6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.9   5.9   5.8   5.6   5.6

In [ ]:
df2[df2<8] = 0

In [ ]:
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan     9.5   9.3   9.1   8.9   8.7   8.5
Kyrgizstan     0.0   0.0   0.0   0.0   0.0   0.0
Turkmenistan   0.0   0.0   0.0   0.0   0.0   0.0

In [ ]:
df2[[2020]]

              2020
Uzbekistan    33.5
Kazakhstan    18.8
Tajikistan     9.5
Kyrgizstan     0.0
Turkmenistan   0.0

## `.loc` va `.iloc`
`.loc` yordamida qator va ustunlani ularning nomi bo'yicha tanlash mumkin.

In [ ]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df.loc[[2015]]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df.loc[[2017,2020]]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2017        31.9        18.1         8.9         6.2           5.8
2020        33.5        18.8         9.5         6.5           6.0

In [ ]:
df.loc[[2020,2019],['Uzbekistan','Kazakhstan']]

      Uzbekistan  Kazakhstan
2020        33.5        18.8
2019        32.9        18.5

`.iloc` yordamida qator va ustunlani ularning tartib raqami bo'yicha tanlash mumkin

In [ ]:
df.iloc[[0,2,4]]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2018        32.5        18.3         9.1         6.3           5.9
2016        31.4        17.8         8.7         6.1           5.6

In [ ]:
df.iloc[[0],[0,3,4]]

      Uzbekistan  Kyrgizstan  Turkmenistan
2020        33.5         6.5           6.0

In [ ]:
df.loc[:2017,'Uzbekistan']

2020    33.5
2019    32.9
2018    32.5
2017    31.9
Name: Uzbekistan, dtype: float64

## Sonli indekslar

`pandas` obyektlariga indeks orqali murojaat qilish biroz mujmal tuyulishi mumkin. Bunga sabab biz o'rganib qolgan list va tuple ma'lumot turlari bilan ishlashdagi farq.

Misol uchun, Pythonda ro'yxatning oxirgi elementini ko'rish uchun -1 indeksi orqali murojaat qilishimiz mumkin:

In [ ]:
nums = list(range(0,11))
nums

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
nums[-1] # nums oxirgi elementi

10

Yuqoridagi usulni sonli indeksga ega `Series` ma'lumot tuzilmasiga qo'llab ko'ramiz:

In [ ]:
nums = pd.Series(np.arange(10.))
nums

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [ ]:
nums[-1]

KeyError: -1

Ko'rib turganingizdek bu usul raqamli indekslar bilan ishlamas ekan. Agar indesklar raqamli emas, matn bo'lsachi?

In [ ]:
ser = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
ser

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
ser[-1]

4.0

Bu holda esa xato yo'q.

Muammoning yechimi doimo `.loc` yoki `.iloc` parametrlaridan foydalanish

In [ ]:
nums.iloc[-1]

9.0

In [ ]:
nums.iloc[4]

4.0

In [ ]:
ser.loc['d']

3.0